# Generated by Django 5.1.1 on 2024-09-23 13:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('store_id', models.CharField(max_length=32, unique=True)),
                ('timezone', models.CharField(default='America/Chicago', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='StoreHours',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(default=0)),
                ('start_time_local', models.TimeField(default='00:00:00')),
                ('end_time_local', models.TimeField(default='23:59:59')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreStatus',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=32)),
                ('timestamp_utc', models.DateTimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.store')),
            ],
        ),
    ]
