# Generated by Django 5.1.1 on 2024-09-24 05:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_load_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('report_id', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('report', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Complete', 'Complete')], default='Running', max_length=32)),
            ],
        ),
    ]
