# Generated by Django 5.1.1 on 2024-09-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.TextField(blank=True),
        ),
    ]
